[[holidays]]
date = 1984-01-01
name = "元日"
weekday = "日"

[[holidays]]
date = 1984-01-02
name = "休日"
weekday = "月"

[[holidays]]
date = 1984-01-15
name = "成人の日"
weekday = "日"

[[holidays]]
date = 1984-01-16
name = "休日"
weekday = "月"

[[holidays]]
date = 1984-02-11
name = "建国記念の日"
weekday = "土"

[[holidays]]
date = 1984-03-20
name = "春分の日"
weekday = "火"

[[holidays]]
date = 1984-04-29
name = "天皇誕生日"
weekday = "日"

[[holidays]]
date = 1984-04-30
name = "休日"
weekday = "月"

[[holidays]]
date = 1984-05-03
name = "憲法記念日"
weekday = "木"

[[holidays]]
date = 1984-05-05
name = "こどもの日"
weekday = "土"

[[holidays]]
date = 1984-09-15
name = "敬老の日"
weekday = "土"

[[holidays]]
date = 1984-09-23
name = "秋分の日"
weekday = "日"

[[holidays]]
date = 1984-09-24
name = "休日"
weekday = "月"

[[holidays]]
date = 1984-10-10
name = "体育の日"
weekday = "水"

[[holidays]]
date = 1984-11-03
name = "文化の日"
weekday = "土"

[[holidays]]
date = 1984-11-23
name = "勤労感謝の日"
weekday = "金"
